<?php

/**
 * @file
 * Site info section for DLAW settings.
 */

/**
 * Implements hook_menu().
 */
function dlawsettings_menu_menu() {
  $items['admin/dashboard/settings/menu'] = array(
    'title' => 'Menu',
    'page callback' => 'dlawsettings_menu_list',
    'access arguments' => array('administer dlaw settings'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );

  return $items;
}

/**
 * Callback for menu admin/dashboard/settings/menu.
 */
function dlawsettings_menu_list() {

  $result = db_query("SELECT * FROM {menu_custom} ORDER BY title", array(), array('fetch' => PDO::FETCH_ASSOC));
  $header = array(t('Title'), array('data' => t('Operations'), 'colspan' => '2'));
  $rows = array();
  foreach ($result as $menu) {
    if (user_access('administer '. $menu['menu_name'] .' menu items')) {
      $row = array(theme('menu_admin_overview', array('title' => $menu['title'], 'name' => $menu['menu_name'], 'description' => $menu['description'])));
      $row[] = array('data' => l(t('list links'), 'admin/structure/menu/manage/' . $menu['menu_name']));
      $row[] = array('data' => l(t('add link'), 'admin/structure/menu/manage/' . $menu['menu_name'] . '/add'));
      $rows[] = $row;
    }
  }
  return theme('table', array('header' => $header, 'rows' => $rows));
}


