<?php

/**
 * @file
 * Environment indicator very light.
 * Forked version for UI internal use.
 * It works with admin user (uid=1) only.
 */

/**
 * Implements hook_init().
 */
function simplei_init() {
  global $conf, $user;

  if ($user->uid == 1 and !empty($conf['simple_environment_indicator'])) {
    // $indicator[0] = indicator color, $indicator[1] = indicator text
    $indicator = explode(' ', str_replace('  ', ' ', $conf['simple_environment_indicator']), 2);

    if (module_exists('toolbar')) {
      $css = "#toolbar div.toolbar-menu { background: $indicator[0]; }";

      if (!empty($indicator[1])) {
        $css .= "#toolbar-home a span { display: none; }";
        $css .= "#toolbar-home a:before { content: '$indicator[1]'; }";
      }
    }
    elseif (module_exists('admin_menu')) {
      $css = "#admin-menu { background: $indicator[0]; }";

      if (!empty($indicator[1])) {
        $css .= "#admin-menu .dropdown .admin-menu-icon > a span { display: none; }";
        $css .= "#admin-menu .dropdown .admin-menu-icon > a:before { content: '$indicator[1]'; }";
      }
    }

    drupal_add_css($css, array('type' => 'inline', 'weight' => 10));
  }
}
